name: Post to X (Twitter)

on:
  workflow_dispatch:  # 手動で実行できるトリガー
  schedule:
    - cron: '0 9 * * *'  # 毎日9時に実行（必要に応じて調整）

jobs:
  post_to_x:
    runs-on: ubuntu-latest  # 最新のUbuntu環境で実行

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # リポジトリのコードを取得

    - name: Set up Python
      uses: actions/setup-python@v4  # Python環境をセットアップ
      with:
        python-version: '3.9'  # 使用するPythonのバージョン

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 必要なライブラリをインストール

    - name: Run Python script to post to X
      env:  # GitHub Secretsから環境変数を設定
        X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}  # Bearer Tokenを設定
      run: python scripts/gemini_to_x.py  # スクリプトを実行
